# Generated by Django 6.0.2 on 2026-02-09 01:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ivatan_term', models.CharField(max_length=255)),
                ('syllabication', models.CharField(blank=True, max_length=255)),
                ('phonetic', models.CharField(blank=True, max_length=255)),
                ('part_of_speech', models.CharField(blank=True, choices=[('noun', 'Noun'), ('verb', 'Verb'), ('adjective', 'Adjective'), ('adverb', 'Adverb'), ('other', 'Other')], max_length=20)),
                ('english_meaning', models.TextField()),
                ('example_sentence', models.TextField(blank=True)),
                ('inflected_forms', models.TextField(blank=True)),
                ('etymology', models.TextField(blank=True)),
                ('variant', models.CharField(choices=[('isamurong', 'Isamurong'), ('ivasay', 'Ivasay'), ('itbayaten', 'Itbayaten'), ('isabtang', 'Isabtang'), ('general', 'General Ivatan')], default='general', max_length=20)),
                ('source', models.TextField()),
                ('self_knowledge', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dictionary_entries', to=settings.AUTH_USER_MODEL)),
                ('last_revised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revised_dictionary_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AudioPronunciation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('audio_file', models.FileField(upload_to='audio_pronunciations/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audio_contributions', to=settings.AUTH_USER_MODEL)),
                ('dictionary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_pronunciations', to='dictionary.dictionaryentry')),
            ],
        ),
    ]
