# Generated by Django 6.0.2 on 2026-02-09 02:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('english_meaning', models.TextField(blank=True)),
                ('example_sentence', models.TextField(blank=True)),
                ('usage_notes', models.TextField(blank=True)),
                ('synonyms', models.TextField(blank=True)),
                ('antonyms', models.TextField(blank=True)),
                ('etymology', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dictionary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='dictionary.dictionaryentry')),
                ('revised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dictionary_revisions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
