# Generated by Django 6.0.2 on 2026-02-09 02:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0002_dictionaryrevision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictionaryIllustration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='dictionary/illustrations/')),
                ('source_type', models.CharField(choices=[('own', 'Own photo'), ('external', 'External source')], max_length=20)),
                ('source_text', models.TextField(blank=True, help_text='Attribution or source URL if external; optional description if own photo.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dictionary_illustrations', to=settings.AUTH_USER_MODEL)),
                ('dictionary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='illustrations', to='dictionary.dictionaryentry')),
            ],
        ),
    ]
