# Generated by Django 6.0.2 on 2026-02-09 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0003_dictionaryillustration'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='example_translation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dictionaryrevision',
            name='example_translation',
            field=models.TextField(blank=True),
        ),
    ]
