# Generated by Django 6.0.2 on 2026-02-09 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0004_dictionaryentry_example_translation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryentry',
            name='source',
            field=models.TextField(blank=True),
        ),
    ]
