# Generated by Django 6.0.2 on 2026-02-09 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_alter_dictionaryentry_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='canonical_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='variant_terms', to='dictionary.dictionaryentry'),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='usage_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dictionaryentry',
            name='variant',
            field=models.CharField(choices=[('general', 'General Ivatan'), ('isamurong', 'Isamurong'), ('ivasay', 'Ivasay'), ('itbayaten', 'Itbayaten'), ('isabtang', 'Isabtang')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='dictionaryillustration',
            name='source_text',
            field=models.TextField(blank=True, help_text='Attribution or URL if external'),
        ),
    ]
