# Generated by Django 6.0.2 on 2026-02-09 06:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0006_dictionaryentry_canonical_term_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='canonical_term',
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='antonyms',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='dictionaryentry',
            name='synonyms',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='audiopronunciation',
            name='contributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='audiopronunciation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='dictionaryrevision',
            name='revised_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='DictionaryIllustration',
        ),
    ]
