# Generated by Django 6.0.2 on 2026-02-09 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0007_remove_dictionaryentry_canonical_term_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionaryentry',
            name='parent_term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='dictionary.dictionaryentry'),
        ),
    ]
