# Generated by Django 6.0.2 on 2026-02-10 03:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0008_dictionaryentry_parent_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='contributor',
        ),
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='last_revised_by',
        ),
        migrations.RemoveField(
            model_name='dictionaryentry',
            name='parent_term',
        ),
        migrations.RemoveField(
            model_name='dictionaryrevision',
            name='dictionary_entry',
        ),
        migrations.RemoveField(
            model_name='dictionaryrevision',
            name='revised_by',
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=255)),
                ('meaning', models.TextField()),
                ('part_of_speech', models.CharField(max_length=100)),
                ('last_approved_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initial_contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='initial_entries', to=settings.AUTH_USER_MODEL)),
                ('last_approved_by', models.ManyToManyField(related_name='approved_entries', to=settings.AUTH_USER_MODEL)),
                ('last_revised_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_revised_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EntryRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term', models.CharField(max_length=255)),
                ('meaning', models.TextField()),
                ('part_of_speech', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_revisions', to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='dictionary.entry')),
            ],
        ),
        migrations.DeleteModel(
            name='AudioPronunciation',
        ),
        migrations.DeleteModel(
            name='DictionaryEntry',
        ),
        migrations.DeleteModel(
            name='DictionaryRevision',
        ),
    ]
