# Generated by Django 6.0.2 on 2026-02-10 05:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0009_remove_dictionaryentry_contributor_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='last_approved_by',
            field=models.ManyToManyField(related_name='entries_approved', to=settings.AUTH_USER_MODEL),
        ),
    ]
