# Generated by Django 6.0.2 on 2026-02-10 05:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0010_alter_entry_last_approved_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mother_entry', models.OneToOneField(blank=True, help_text='Authoritative (mother) term for this variant group.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother_of_group', to='dictionary.entry')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='variant_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='dictionary.variantgroup'),
        ),
    ]
