# Generated by Django 6.0.2 on 2026-02-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0011_variantgroup_entry_variant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryrevision',
            name='inflected_forms',
            field=models.JSONField(blank=True, default=dict, help_text='Variant-specific inflected forms. Keys validated against mother part of speech.'),
        ),
    ]
