# Generated by Django 6.0.2 on 2026-02-11 05:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0012_entryrevision_inflected_forms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entryrevision',
            name='inflected_forms',
        ),
        migrations.RemoveField(
            model_name='entryrevision',
            name='meaning',
        ),
        migrations.RemoveField(
            model_name='entryrevision',
            name='part_of_speech',
        ),
        migrations.RemoveField(
            model_name='entryrevision',
            name='term',
        ),
        migrations.RemoveField(
            model_name='entryrevision',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='entry',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='audio_pronunciation',
            field=models.FileField(blank=True, null=True, upload_to='dictionary/audio/'),
        ),
        migrations.AddField(
            model_name='entry',
            name='audio_source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='english_antonym',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='english_synonym',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='etymology',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='example_sentence',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='example_translation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='inflected_forms',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='entry',
            name='is_mother',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='ivatan_antonym',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='ivatan_synonym',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dictionary/photos/'),
        ),
        migrations.AddField(
            model_name='entry',
            name='photo_source',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='pronunciation_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='entry',
            name='source_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('approved_under_review', 'Approved (Under Review)'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=30),
        ),
        migrations.AddField(
            model_name='entry',
            name='usage_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='variant_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='entryrevision',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entryrevision',
            name='proposed_data',
            field=models.JSONField(default=dict, help_text='Full proposed snapshot of entry fields.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entry',
            name='last_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='last_approved_by',
            field=models.ManyToManyField(blank=True, related_name='approved_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='last_revised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='last_revised_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entry',
            name='meaning',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='part_of_speech',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='entryrevision',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='variantgroup',
            name='mother_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mother_of_group', to='dictionary.entry'),
        ),
    ]
