# Generated by Django 5.0.4 on 2026-02-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_remove_entryrevision_inflected_forms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('approved_under_review', 'Approved (Under Review)'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=30),
        ),
    ]
