# Generated by Django 5.0.4 on 2026-02-11 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0014_alter_entry_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryrevision',
            name='is_base_snapshot',
            field=models.BooleanField(default=False),
        ),
    ]
