# Generated by Django 5.0.4 on 2026-02-11 11:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_entryrevision_is_base_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='audio_contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audio_contributed_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='audio_source_is_self_recorded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='photo_contributor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photo_contributed_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entry',
            name='photo_source_is_contributor_owned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entry',
            name='term_source_is_self_knowledge',
            field=models.BooleanField(default=False),
        ),
    ]
