# Generated by Django 6.0.2 on 2026-02-09 01:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolkloreEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('category', models.CharField(choices=[('myth', 'Myth'), ('legend', 'Legend'), ('laji', 'Laji'), ('poem', 'Poem'), ('proverb', 'Proverb'), ('idiom', 'Idiom')], max_length=20)),
                ('variant', models.CharField(choices=[('isamurong', 'Isamurong'), ('ivasay', 'Ivasay'), ('itbayaten', 'Itbayaten'), ('isabtang', 'Isabtang'), ('general', 'General Ivatan')], default='general', max_length=20)),
                ('source', models.TextField()),
                ('self_knowledge', models.BooleanField(default=False)),
                ('media_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='folklore_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
