# Generated by Django 5.0.4 on 2026-02-11 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folklore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folkloreentry',
            name='variant',
        ),
        migrations.AddField(
            model_name='folkloreentry',
            name='copyright_usage',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='folkloreentry',
            name='media_source',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='folkloreentry',
            name='municipality_source',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='folkloreentry',
            name='self_produced_media',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='folkloreentry',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('approved_under_review', 'Approved (Under Review)'), ('rejected', 'Rejected'), ('archived', 'Archived'), ('deleted', 'Deleted')], default='draft', max_length=30),
        ),
    ]
