# Generated by Django 5.0.4 on 2026-02-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folklore', '0002_remove_folkloreentry_variant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folkloreentry',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
