# Generated by Django 6.0.2 on 2026-06-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folklore', '0006_folklore_taxonomy'),
    ]

    operations = [
        migrations.AddField(
            model_name='folklorerevision',
            name='revision_type',
            field=models.CharField(choices=[('revision', 'Revision'), ('variant', 'Variant')], default='revision', max_length=20),
        ),
        migrations.AddField(
            model_name='folklorerevision',
            name='variant_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variant_revisions', to='folklore.folkloreentry'),
        ),
    ]
