# Generated by Django 5.0.4 on 2026-02-11 08:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0013_remove_entryrevision_inflected_forms_and_more'),
        ('reviews', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='review',
            name='review_round',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='decision',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('flag', 'Flag for Re-review')], max_length=10),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(fields=('revision', 'reviewer', 'review_round'), name='uniq_review_reviewer_per_round'),
        ),
    ]
