# Generated by Django 5.0.4 on 2026-02-11 11:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0015_entryrevision_is_base_snapshot'),
        ('folklore', '0002_remove_folkloreentry_variant_and_more'),
        ('reviews', '0002_alter_review_unique_together_review_review_round_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAdminOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('dictionary', 'Dictionary'), ('folklore', 'Folklore')], max_length=20)),
                ('action', models.CharField(choices=[('force_reject', 'Force Reject'), ('restore_approved', 'Restore Approved'), ('archive', 'Archive')], max_length=20)),
                ('notes', models.TextField()),
                ('status_before', models.CharField(max_length=30)),
                ('status_after', models.CharField(max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='review_overrides', to=settings.AUTH_USER_MODEL)),
                ('dictionary_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_overrides', to='dictionary.entry')),
                ('folklore_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_overrides', to='folklore.folkloreentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
