# Generated by Django 5.0.4 on 2026-06-12 04:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0017_entry_phonetic'),
        ('folklore', '0006_folklore_taxonomy'),
        ('reviews', '0005_folklorereview_folklore_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='folklorereview',
            name='decision',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('flag', 'Flag for Re-review'), ('return', 'Return for Fixing')], max_length=10),
        ),
        migrations.AlterField(
            model_name='review',
            name='decision',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('flag', 'Flag for Re-review'), ('return', 'Return for Fixing')], max_length=10),
        ),
        migrations.CreateModel(
            name='CorrectionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(choices=[('dictionary', 'Dictionary'), ('folklore', 'Folklore')], max_length=20)),
                ('scope', models.CharField(choices=[('original', 'Original Entry'), ('revision', 'Approved Revision')], max_length=20)),
                ('notes', models.TextField()),
                ('source_snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('open', 'Open'), ('submitted', 'Submitted'), ('resolved', 'Resolved')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correction_assignments', to=settings.AUTH_USER_MODEL)),
                ('dictionary_correction_revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_assignment', to='dictionary.entryrevision')),
                ('dictionary_source_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_correction_assignments', to='dictionary.entryrevision')),
                ('folklore_correction_revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correction_assignment', to='folklore.folklorerevision')),
                ('folklore_source_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='source_correction_assignments', to='folklore.folklorerevision')),
                ('returned_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='corrections_returned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
