# Generated by Django 6.0.2 on 2026-06-23 07:45

import django.db.models.deletion
import resources.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('file', models.FileField(help_text='Accepted formats: PDF, PPT, PPTX, PPS, PPSX.', storage=resources.models.private_storage, upload_to='resources/', validators=[resources.models.validate_resource_file])),
                ('visibility', models.CharField(choices=[('public', 'All stewards'), ('members', 'Members only (logged in)'), ('admin', 'Admins and reviewers only')], default='public', help_text='Who is allowed to open this document.', max_length=20)),
                ('is_published', models.BooleanField(default=True, help_text='Untick to hide the document without deleting it.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_resources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
