# Generated by Django 5.0.4 on 2026-02-11 08:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dictionary', '0015_entryrevision_is_base_snapshot'),
        ('folklore', '0002_remove_folkloreentry_variant_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContributionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('contribution_type', models.CharField(choices=[('dictionary_term', 'Dictionary Term'), ('folklore_entry', 'Folklore Entry'), ('revision', 'Revision')], max_length=32)),
                ('awarded_at', models.DateTimeField(auto_now_add=True)),
                ('dictionary_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_events', to='dictionary.entry')),
                ('entry_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_events', to='dictionary.entryrevision')),
                ('folklore_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contribution_events', to='folklore.folkloreentry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-awarded_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(blank=True, default='', max_length=255)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='users/profile_photos/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='contributionevent',
            constraint=models.UniqueConstraint(condition=models.Q(('contribution_type', 'revision')), fields=('user', 'dictionary_entry', 'contribution_type'), name='uniq_revision_credit_per_user_entry'),
        ),
        migrations.AddConstraint(
            model_name='contributionevent',
            constraint=models.UniqueConstraint(condition=models.Q(('contribution_type', 'dictionary_term')), fields=('user', 'dictionary_entry', 'contribution_type'), name='uniq_dictionary_term_credit_per_user_entry'),
        ),
        migrations.AddConstraint(
            model_name='contributionevent',
            constraint=models.UniqueConstraint(condition=models.Q(('contribution_type', 'folklore_entry')), fields=('user', 'folklore_entry', 'contribution_type'), name='uniq_folklore_credit_per_user_entry'),
        ),
    ]
