# Generated by Django 5.0.4 on 2026-02-27 06:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_roleapplication_roleapplicationdecision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MunicipalityStats',
            fields=[
                ('municipality', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('dictionary_all_time', models.PositiveIntegerField(default=0)),
                ('folklore_all_time', models.PositiveIntegerField(default=0)),
                ('combined_all_time', models.PositiveIntegerField(default=0)),
                ('dictionary_month', models.PositiveIntegerField(default=0)),
                ('folklore_month', models.PositiveIntegerField(default=0)),
                ('combined_month', models.PositiveIntegerField(default=0)),
                ('last_month_calculated', models.CharField(blank=True, default='', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['municipality'],
            },
        ),
        migrations.CreateModel(
            name='RecognitionEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('municipality', models.CharField(blank=True, default='', max_length=100)),
                ('event_type', models.CharField(choices=[('level_up', 'Level Up'), ('badge_unlock', 'Badge Unlock'), ('municipality_win', 'Municipality Win')], max_length=32)),
                ('reference_id', models.CharField(blank=True, default='', max_length=120)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recognition_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='users_recog_event_t_dbd40b_idx'), models.Index(fields=['municipality', 'created_at'], name='users_recog_municip_2ddbd0_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserContributionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combined_total', models.PositiveIntegerField(default=0)),
                ('dictionary_original_total', models.PositiveIntegerField(default=0)),
                ('folklore_original_total', models.PositiveIntegerField(default=0)),
                ('total_rejections', models.PositiveIntegerField(default=0)),
                ('review_completed_total', models.PositiveIntegerField(default=0)),
                ('dictionary_month', models.PositiveIntegerField(default=0)),
                ('folklore_month', models.PositiveIntegerField(default=0)),
                ('combined_month', models.PositiveIntegerField(default=0)),
                ('last_month_calculated', models.CharField(blank=True, default='', max_length=7)),
                ('contributor_level', models.PositiveSmallIntegerField(default=0)),
                ('reviewer_level', models.PositiveSmallIntegerField(default=0)),
                ('unlocked_badges', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['combined_total'], name='users_userc_combine_f2540b_idx'), models.Index(fields=['dictionary_original_total'], name='users_userc_diction_029a61_idx'), models.Index(fields=['folklore_original_total'], name='users_userc_folklor_5a3a7f_idx'), models.Index(fields=['review_completed_total'], name='users_userc_review__1b4ee9_idx'), models.Index(fields=['last_month_calculated'], name='users_userc_last_mo_aa676e_idx')],
            },
        ),
    ]
