# Generated by Django 5.0.4 on 2026-02-27 07:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_municipalitystats_recognitionevent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GamificationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=50, unique=True)),
                ('contributor_levels', models.JSONField(blank=True, default=list)),
                ('reviewer_levels', models.JSONField(blank=True, default=list)),
                ('dictionary_badges', models.JSONField(blank=True, default=list)),
                ('folklore_badges', models.JSONField(blank=True, default=list)),
                ('quality_badge', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GamificationRuntimeState',
            fields=[
                ('key', models.CharField(default='global', max_length=32, primary_key=True, serialize=False)),
                ('last_winner_processed_month', models.CharField(blank=True, default='', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MunicipalityMonthlyWinner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month_key', models.CharField(max_length=7)),
                ('metric', models.CharField(choices=[('dictionary', 'Dictionary'), ('folklore', 'Folklore'), ('combined', 'Combined')], max_length=16)),
                ('municipality', models.CharField(max_length=100)),
                ('score', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-month_key', 'metric'],
            },
        ),
        migrations.AddConstraint(
            model_name='municipalitymonthlywinner',
            constraint=models.UniqueConstraint(fields=('month_key', 'metric'), name='uniq_municipality_winner_per_month_metric'),
        ),
    ]
