# Generated by Django 5.0.4 on 2026-06-04 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usersessionevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='include_in_leaderboard',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='SiteContentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=32, unique=True)),
                ('about_heading', models.CharField(blank=True, default='', max_length=160)),
                ('about_intro_paragraphs', models.JSONField(blank=True, default=list)),
                ('about_body_paragraphs', models.JSONField(blank=True, default=list)),
                ('about_rationale_paragraphs', models.JSONField(blank=True, default=list)),
                ('about_future_paragraphs', models.JSONField(blank=True, default=list)),
                ('about_final_quote', models.TextField(blank=True, default='')),
                ('yaru_heading', models.CharField(blank=True, default='', max_length=160)),
                ('yaru_intro_paragraphs', models.JSONField(blank=True, default=list)),
                ('support_statements', models.JSONField(blank=True, default=list)),
                ('partner_details', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_content_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Site content settings',
                'verbose_name_plural': 'Site content settings',
            },
        ),
    ]
