# Generated by Django 5.0.4 on 2026-06-06 14:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_sitecontentsettings_brand_landing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccountAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('deactivate', 'Deactivate'), ('reactivate', 'Reactivate'), ('send_password_reset', 'Send Password Reset'), ('revoke_role', 'Revoke Role'), ('flag_suspicious', 'Flag Suspicious'), ('clear_suspicious_flag', 'Clear Suspicious Flag'), ('confirm_suspicious_flag', 'Confirm Suspicious Flag')], max_length=32)),
                ('role', models.CharField(blank=True, default='', max_length=24)),
                ('notes', models.TextField(blank=True, default='')),
                ('status_before', models.CharField(blank=True, default='', max_length=80)),
                ('status_after', models.CharField(blank=True, default='', max_length=80)),
                ('flag_status', models.CharField(choices=[('none', 'None'), ('pending', 'Pending'), ('cleared', 'Cleared'), ('confirmed', 'Confirmed')], default='none', max_length=16)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admin_account_actions_taken', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='admin_account_flags_resolved', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_account_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['target_user', 'created_at'], name='users_admin_target__ca3139_idx'), models.Index(fields=['action', 'flag_status', 'created_at'], name='users_admin_action_e42dc9_idx')],
            },
        ),
    ]
