# Generated by Django 5.0.4 on 2026-06-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_adminaccountaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontentsettings',
            name='contributor_agreement_paragraphs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitecontentsettings',
            name='media_upload_policy_paragraphs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='sitecontentsettings',
            name='privacy_notice_paragraphs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
