# Generated by Django 5.0.4 on 2026-06-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_notification_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='target_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('submission_received', 'Submission received'), ('revision_approved', 'Revision approved'), ('revision_rejected', 'Revision rejected'), ('milestone', 'Milestone'), ('comment_received', 'Comment on your entry'), ('role_decided', 'Role application decided')], max_length=32),
        ),
    ]
