# Generated by Django 5.0.4 on 2026-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_notification_feedback_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_prompt_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_prompt_pending',
            field=models.BooleanField(default=False),
        ),
    ]
