# Generated by Django 5.0.4 on 2026-06-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_name_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminaccountaction',
            name='action',
            field=models.CharField(choices=[('deactivate', 'Deactivate'), ('reactivate', 'Reactivate'), ('send_password_reset', 'Send Password Reset'), ('send_approval_reminder', 'Send Approval Reminder'), ('revoke_role', 'Revoke Role'), ('flag_suspicious', 'Flag Suspicious'), ('clear_suspicious_flag', 'Clear Suspicious Flag'), ('confirm_suspicious_flag', 'Confirm Suspicious Flag')], max_length=32),
        ),
    ]
