# Generated by Codex on 2026-07-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0028_admin_approval_reminder_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminaccountaction",
            name="action",
            field=models.CharField(
                choices=[
                    ("deactivate", "Deactivate"),
                    ("reactivate", "Reactivate"),
                    ("send_password_reset", "Send Password Reset"),
                    ("send_approval_reminder", "Send Approval Reminder"),
                    ("revoke_role", "Revoke Role"),
                    ("flag_suspicious", "Flag Suspicious"),
                    ("clear_suspicious_flag", "Clear Suspicious Flag"),
                    ("confirm_suspicious_flag", "Confirm Suspicious Flag"),
                    ("schedule_account_deletion", "Schedule Account Deletion"),
                    ("cancel_account_deletion", "Cancel Account Deletion"),
                    ("complete_account_deletion", "Complete Account Deletion"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="adminaccountaction",
            name="deletion_status",
            field=models.CharField(
                choices=[
                    ("none", "None"),
                    ("pending", "Pending"),
                    ("canceled", "Canceled"),
                    ("completed", "Completed"),
                ],
                default="none",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="adminaccountaction",
            name="deletion_reason",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="adminaccountaction",
            name="scheduled_for",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adminaccountaction",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="adminaccountaction",
            index=models.Index(
                fields=["action", "deletion_status", "scheduled_for"],
                name="users_admin_action_6bddbe_idx",
            ),
        ),
    ]
