const DEFAULT_DICTIONARY_BADGES = [
  { key: 'dictionary-seed', name: 'Word Seed', current_value: 3, threshold: 3, unlocked: true },
  { key: 'dictionary-grove', name: 'Word Grove', current_value: 8, threshold: 10, unlocked: false },
]

const DEFAULT_FOLKLORE_BADGES = [
  { key: 'folklore-voice', name: 'Story Voice', current_value: 1, threshold: 1, unlocked: true },
  { key: 'folklore-keeper', name: 'Archive Keeper', current_value: 2, threshold: 5, unlocked: false },
]

const DEFAULT_QUALITY_BADGES = [
  { key: 'quality-steward', name: 'Steady Steward', current_value: 6, threshold: 10, rejection_count: 0, unlocked: false },
]

const SAMPLE_PROFILE_SEEDS = [
  {
    username: 'kristelle.adami',
    first_name: 'Kristelle Joyce',
    last_name: 'Adami',
    municipality: 'Basco',
    affiliation: 'Chirin Ivatan Project Lead',
    occupation: 'Cultural Digitalization Advocate',
    bio: 'Graduate researcher and cultural worker building digital spaces that help Ivatan language, memory, and identity stay living, teachable, and shareable.',
    joined_date: '2026-01-18',
    photoIndex: 0,
    contributor_accountability: 'Invited by project founder record',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 12, folklore_entries: 4, revisions: 7, total_contributions: 23 },
    contributor_level: { title: 'Language House Builder', current_count: 23 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Helping shape the house that holds words, stories, and shared memory.',
    approved_mother_terms: ['chirin', 'yaru', 'vahay'],
    approved_folklore_entries: ['Ivatan House Wind Song', 'Naidi Dawn Story'],
    entries_revised: ['daktan', 'mayuh', 'arah'],
  },
  {
    username: 'consultant.marinel',
    first_name: 'Marinel',
    last_name: 'Reyes',
    municipality: 'Mahatao',
    affiliation: 'Language and Culture Adviser, Mahatao',
    occupation: 'Language Consultant',
    bio: 'Works with teachers and elders to clarify regional usages, respectful phrasing, and community context for learning materials.',
    joined_date: '2026-02-03',
    photoIndex: 2,
    contributor_accountability: 'Consultant reference through Mahatao partners',
    reviewer_accountability: 'Community consultant, not reviewer',
    contribution_summary: { dictionary_terms: 3, folklore_entries: 1, revisions: 5, total_contributions: 9 },
    contributor_level: { title: 'Cultural Adviser', current_count: 9 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Often helps contributors choose careful wording and place-sensitive meaning notes.',
    approved_mother_terms: ['kapayso', 'dawri'],
    approved_folklore_entries: ['Mahatao Rain Saying'],
    entries_revised: ['yaru', 'chirin'],
  },
  {
    username: 'consultant.leo',
    first_name: 'Leo',
    last_name: 'Mangada',
    municipality: 'Ivana',
    affiliation: 'Heritage Education Adviser, Ivana',
    occupation: 'Heritage Educator',
    bio: 'Supports school-facing explanations so dictionary entries remain academically useful without losing Ivatan nuance.',
    joined_date: '2026-02-05',
    photoIndex: 1,
    contributor_accountability: 'Education partner endorsement',
    reviewer_accountability: 'Community consultant, not reviewer',
    contribution_summary: { dictionary_terms: 2, folklore_entries: 2, revisions: 4, total_contributions: 8 },
    contributor_level: { title: 'Learning Bridge', current_count: 8 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Helps translate community knowledge into school-friendly explanations.',
    approved_mother_terms: ['mavid', 'tayid'],
    approved_folklore_entries: ['Ivana Harbor Memory'],
    entries_revised: ['rayu', 'vakul'],
  },
  {
    username: 'consultant.teresita',
    first_name: 'Teresita',
    last_name: 'Abad',
    municipality: 'Sabtang',
    affiliation: 'Community Knowledge Consultant, Sabtang',
    occupation: 'Community Historian',
    bio: 'Shares oral context, family memory, and usage distinctions that rarely appear in printed materials.',
    joined_date: '2026-02-07',
    photoIndex: 11,
    contributor_accountability: 'Community referral from Sabtang',
    reviewer_accountability: 'Community consultant, not reviewer',
    contribution_summary: { dictionary_terms: 4, folklore_entries: 3, revisions: 3, total_contributions: 10 },
    contributor_level: { title: 'Memory Keeper', current_count: 10 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Adds lived context that helps preserve not just words, but how they are carried.',
    approved_mother_terms: ['raray', 'salakay'],
    approved_folklore_entries: ['Sabtang Sea Crossing'],
    entries_revised: ['kapayso'],
  },
  {
    username: 'reviewer.aimee',
    first_name: 'Aimee',
    last_name: 'Darunday',
    municipality: 'Basco',
    affiliation: 'Dictionary Review Volunteer, Basco',
    occupation: 'Teacher',
    bio: 'Reviews submissions for clarity, attribution, and learner usefulness while keeping community usage front and center.',
    joined_date: '2026-02-12',
    photoIndex: 3,
    contributor_accountability: 'Approved contributor onboarding',
    reviewer_accountability: 'Screened by admin and reviewer quorum',
    contribution_summary: { dictionary_terms: 5, folklore_entries: 1, revisions: 11, total_contributions: 17 },
    contributor_level: { title: 'Steady Contributor', current_count: 17 },
    reviewer_level: { title: 'Trusted Reviewer', current_count: 26 },
    language_headline: 'Known for careful source checking and gentle revision notes.',
    approved_mother_terms: ['vasay', 'danum'],
    approved_folklore_entries: ['Basco Classroom Proverb'],
    entries_revised: ['yaru', 'chirin', 'mayuh'],
  },
  {
    username: 'reviewer.rico',
    first_name: 'Rico',
    last_name: 'Cabardo',
    municipality: 'Sabtang',
    affiliation: 'Folklore Review Volunteer, Sabtang',
    occupation: 'Community Archivist',
    bio: 'Focuses on folklore drafts, helping contributors preserve source context, municipality history, and sensitive details responsibly.',
    joined_date: '2026-02-14',
    photoIndex: 4,
    contributor_accountability: 'Approved contributor onboarding',
    reviewer_accountability: 'Screened by admin and reviewer quorum',
    contribution_summary: { dictionary_terms: 1, folklore_entries: 5, revisions: 8, total_contributions: 14 },
    contributor_level: { title: 'Archive Steward', current_count: 14 },
    reviewer_level: { title: 'Folklore Reviewer', current_count: 18 },
    language_headline: 'Helps stories stay attributable, legible, and culturally careful.',
    approved_mother_terms: ['tidung'],
    approved_folklore_entries: ['Sabtang Evening Chant', 'Story of the Reef Lantern'],
    entries_revised: ['wind at naidi', 'song of iraya cliffs'],
  },
  {
    username: 'reviewer.luz',
    first_name: 'Luz',
    last_name: 'Arriola',
    municipality: 'Uyugan',
    affiliation: 'Community Review Volunteer, Uyugan',
    occupation: 'Community Organizer',
    bio: 'Often reviews entries for readability and municipality context, especially when younger contributors are submitting first drafts.',
    joined_date: '2026-02-15',
    photoIndex: 5,
    contributor_accountability: 'Approved contributor onboarding',
    reviewer_accountability: 'Screened by reviewer quorum',
    contribution_summary: { dictionary_terms: 4, folklore_entries: 2, revisions: 6, total_contributions: 12 },
    contributor_level: { title: 'Yaru Builder', current_count: 12 },
    reviewer_level: { title: 'Community Reviewer', current_count: 15 },
    language_headline: 'A supportive reviewer for first-time contributors.',
    approved_mother_terms: ['hinung', 'saleng'],
    approved_folklore_entries: ['Uyugan Fishing Memory'],
    entries_revised: ['rayu', 'salakay'],
  },
  {
    username: 'reviewer.nestor',
    first_name: 'Nestor',
    last_name: 'Valdez',
    municipality: 'Itbayat',
    affiliation: 'Language Review Volunteer, Itbayat',
    occupation: 'Local Research Assistant',
    bio: 'Helps compare variant wording across islands and flags entries that need another round of verification.',
    joined_date: '2026-02-16',
    photoIndex: 6,
    contributor_accountability: 'Approved contributor onboarding',
    reviewer_accountability: 'Screened by admin and reviewer quorum',
    contribution_summary: { dictionary_terms: 3, folklore_entries: 1, revisions: 9, total_contributions: 13 },
    contributor_level: { title: 'Variant Guide', current_count: 13 },
    reviewer_level: { title: 'Language Reviewer', current_count: 21 },
    language_headline: 'Especially helpful when variant distinctions need a second look.',
    approved_mother_terms: ['kayvot'],
    approved_folklore_entries: ['Itbayat Cliff Tale'],
    entries_revised: ['vahay', 'tidung'],
  },
  {
    username: 'contributor.ana',
    first_name: 'Ana',
    last_name: 'Adriano',
    municipality: 'Basco',
    affiliation: 'Dictionary Contributor, Basco',
    occupation: 'College Student',
    bio: 'Contributes family-used vocabulary, classroom examples, and pronunciation notes from Basco.',
    joined_date: '2026-02-20',
    photoIndex: 7,
    contributor_accountability: 'Invited by reviewer.aimee',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 6, folklore_entries: 0, revisions: 3, total_contributions: 9 },
    contributor_level: { title: 'Word Gatherer', current_count: 9 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'A promising first-wave dictionary contributor.',
    approved_mother_terms: ['davay', 'tamid'],
    approved_folklore_entries: [],
    entries_revised: ['chirin'],
  },
  {
    username: 'contributor.mika',
    first_name: 'Mika',
    last_name: 'Gato',
    municipality: 'Ivana',
    affiliation: 'Story Contributor, Ivana',
    occupation: 'Youth Volunteer',
    bio: 'Records family stories, sayings, and context notes so younger readers can reconnect with Ivatan narrative traditions.',
    joined_date: '2026-02-21',
    photoIndex: 9,
    contributor_accountability: 'Invited by reviewer.rico',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 2, folklore_entries: 3, revisions: 2, total_contributions: 7 },
    contributor_level: { title: 'Story Carrier', current_count: 7 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Keeps family stories present for younger Ivatan readers.',
    approved_mother_terms: ['sadang'],
    approved_folklore_entries: ['Ivana Moonlit Shore', 'Grandmother\'s Boat Saying'],
    entries_revised: ['song of iraya cliffs'],
  },
  {
    username: 'contributor.ramon',
    first_name: 'Ramon',
    last_name: 'Hontiveros',
    municipality: 'Mahatao',
    affiliation: 'Language Contributor, Mahatao',
    occupation: 'Farmer',
    bio: 'Shares field vocabulary, weather expressions, and everyday word usage heard in Mahatao households.',
    joined_date: '2026-02-23',
    photoIndex: 8,
    contributor_accountability: 'Invited by consultant.marinel',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 4, folklore_entries: 1, revisions: 2, total_contributions: 7 },
    contributor_level: { title: 'Field Lexicon Contributor', current_count: 7 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Contributes practical words rooted in daily work and weather.',
    approved_mother_terms: ['matareng', 'sibatan'],
    approved_folklore_entries: ['Mahatao Slope Tale'],
    entries_revised: ['yaru'],
  },
  {
    username: 'contributor.joan',
    first_name: 'Joan',
    last_name: 'Catajay',
    municipality: 'Itbayat',
    affiliation: 'Folklore Contributor, Itbayat',
    occupation: 'Library Assistant',
    bio: 'Collects oral narratives and helps turn them into readable drafts while preserving the original voice.',
    joined_date: '2026-02-24',
    photoIndex: 10,
    contributor_accountability: 'Invited by reviewer.nestor',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 1, folklore_entries: 4, revisions: 1, total_contributions: 6 },
    contributor_level: { title: 'Folklore Recorder', current_count: 6 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Strongest in folklore capture and preserving narrative cadence.',
    approved_mother_terms: [],
    approved_folklore_entries: ['Itbayat Cliff Tale', 'Returning Tide Story'],
    entries_revised: ['wind at naidi'],
  },
  {
    username: 'contributor.karlo',
    first_name: 'Karlo',
    last_name: 'Dima',
    municipality: 'Uyugan',
    affiliation: 'Community Contributor, Uyugan',
    occupation: 'Barangay Youth Volunteer',
    bio: 'Contributes municipality-based variants and everyday phrases gathered through family conversations.',
    joined_date: '2026-02-26',
    photoIndex: 4,
    contributor_accountability: 'Invited by reviewer.luz',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 3, folklore_entries: 1, revisions: 2, total_contributions: 6 },
    contributor_level: { title: 'Community Contributor', current_count: 6 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Helps widen municipality representation in the archive.',
    approved_mother_terms: ['tayang'],
    approved_folklore_entries: ['Uyugan Creek Story'],
    entries_revised: ['rayu'],
  },
  {
    username: 'contributor.elena',
    first_name: 'Elena',
    last_name: 'Fajardo',
    municipality: 'Basco',
    affiliation: 'Pronunciation Contributor, Basco',
    occupation: 'Speech Coach',
    bio: 'Enjoys helping entries become easier to pronounce by younger learners and non-Ivatan visitors.',
    joined_date: '2026-02-27',
    photoIndex: 5,
    contributor_accountability: 'Invited by reviewer.aimee',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 3, folklore_entries: 0, revisions: 4, total_contributions: 7 },
    contributor_level: { title: 'Pronunciation Guide', current_count: 7 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Adds sound guidance that makes entries more teachable.',
    approved_mother_terms: ['hunget'],
    approved_folklore_entries: [],
    entries_revised: ['vahay', 'mayuh'],
  },
  {
    username: 'contributor.miguel',
    first_name: 'Miguel',
    last_name: 'Alcantara',
    municipality: 'Mahatao',
    affiliation: 'Oral History Contributor, Mahatao',
    occupation: 'Community Volunteer',
    bio: 'Documents oral-history fragments and helps connect them with words still heard in local conversation.',
    joined_date: '2026-03-01',
    photoIndex: 1,
    contributor_accountability: 'Invited by consultant.leo',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 2, folklore_entries: 2, revisions: 2, total_contributions: 6 },
    contributor_level: { title: 'Oral History Contributor', current_count: 6 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Brings oral history and lexical context together.',
    approved_mother_terms: ['malidi'],
    approved_folklore_entries: ['Mahatao Elder Memory'],
    entries_revised: ['tidung'],
  },
  {
    username: 'contributor.carmen',
    first_name: 'Carmen',
    last_name: 'Lopez',
    municipality: 'Sabtang',
    affiliation: 'Proverb Contributor, Sabtang',
    occupation: 'Homemaker',
    bio: 'Shares family sayings and proverbs, especially those that younger relatives no longer hear as often.',
    joined_date: '2026-03-02',
    photoIndex: 2,
    contributor_accountability: 'Invited by reviewer.rico',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 2, folklore_entries: 2, revisions: 1, total_contributions: 5 },
    contributor_level: { title: 'Proverb Gatherer', current_count: 5 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Helps preserve short forms of wisdom and everyday memory.',
    approved_mother_terms: ['mapia'],
    approved_folklore_entries: ['Sabtang Proverb Chain'],
    entries_revised: ['yaru'],
  },
  {
    username: 'ysabel.delacruz',
    first_name: 'Ysabel',
    last_name: 'Dela Cruz',
    municipality: 'Basco',
    affiliation: 'Top Monthly Contributor',
    occupation: 'Teacher',
    bio: 'One of the most active sample contributors, often adding classroom-friendly definitions and example usage.',
    joined_date: '2026-03-04',
    photoIndex: 0,
    contributor_accountability: 'Invited by reviewer.aimee',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 9, folklore_entries: 2, revisions: 6, total_contributions: 17 },
    contributor_level: { title: 'Monthly Front Runner', current_count: 17 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Regularly contributes clear, learner-friendly dictionary entries.',
    approved_mother_terms: ['chirin', 'yaru'],
    approved_folklore_entries: ['Basco Learning Song'],
    entries_revised: ['rayu', 'vakul'],
  },
  {
    username: 'mark.apuyan',
    first_name: 'Mark',
    last_name: 'Apuyan',
    municipality: 'Mahatao',
    affiliation: 'Sample Contributor',
    occupation: 'Farmer',
    bio: 'Contributes place-rooted vocabulary and work-day expressions.',
    joined_date: '2026-03-05',
    photoIndex: 1,
    contributor_accountability: 'Invited by consultant.marinel',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 7, folklore_entries: 1, revisions: 3, total_contributions: 11 },
    contributor_level: { title: 'Field Contributor', current_count: 11 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Strong in words tied to place, work, and weather.',
    approved_mother_terms: ['danum'],
    approved_folklore_entries: ['Mahatao Slope Memory'],
    entries_revised: ['chirin'],
  },
  {
    username: 'lian.darunday',
    first_name: 'Lian',
    last_name: 'Darunday',
    municipality: 'Ivana',
    affiliation: 'Sample Contributor',
    occupation: 'Student Volunteer',
    bio: 'Helps digitize community knowledge for younger audiences.',
    joined_date: '2026-03-05',
    photoIndex: 2,
    contributor_accountability: 'Invited by consultant.leo',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 6, folklore_entries: 2, revisions: 2, total_contributions: 10 },
    contributor_level: { title: 'Youth Yaru Contributor', current_count: 10 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Brings a younger learner perspective into entry writing.',
    approved_mother_terms: ['salin'],
    approved_folklore_entries: ['Ivana Harbor Story'],
    entries_revised: ['yaru'],
  },
  {
    username: 'celina.nuguit',
    first_name: 'Celina',
    last_name: 'Nuguit',
    municipality: 'Uyugan',
    affiliation: 'Sample Contributor',
    occupation: 'Community Volunteer',
    bio: 'Adds community expressions and usage notes tied to local routines.',
    joined_date: '2026-03-06',
    photoIndex: 3,
    contributor_accountability: 'Invited by reviewer.luz',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 5, folklore_entries: 1, revisions: 3, total_contributions: 9 },
    contributor_level: { title: 'Usage Note Contributor', current_count: 9 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Often adds the context that makes a word easier to use well.',
    approved_mother_terms: ['tayang'],
    approved_folklore_entries: ['Uyugan Creek Story'],
    entries_revised: ['mayuh'],
  },
  {
    username: 'rogelio.casta',
    first_name: 'Rogelio',
    last_name: 'Casta',
    municipality: 'Sabtang',
    affiliation: 'Sample Contributor',
    occupation: 'Boatman',
    bio: 'Shares sea-going terms and local phrases tied to crossing and weather.',
    joined_date: '2026-03-07',
    photoIndex: 4,
    contributor_accountability: 'Invited by reviewer.rico',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 5, folklore_entries: 1, revisions: 2, total_contributions: 8 },
    contributor_level: { title: 'Sea Lexicon Contributor', current_count: 8 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Brings sea and travel vocabulary into the archive.',
    approved_mother_terms: ['tayid'],
    approved_folklore_entries: ['Sabtang Crossing Tale'],
    entries_revised: ['vakul'],
  },
  {
    username: 'nica.esguerra',
    first_name: 'Nica',
    last_name: 'Esguerra',
    municipality: 'Itbayat',
    affiliation: 'Sample Contributor',
    occupation: 'Student',
    bio: 'Collects remembered family words and songs from Itbayat relatives.',
    joined_date: '2026-03-07',
    photoIndex: 5,
    contributor_accountability: 'Invited by reviewer.nestor',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 4, folklore_entries: 2, revisions: 2, total_contributions: 8 },
    contributor_level: { title: 'Island Memory Contributor', current_count: 8 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Preserves words and stories passed through family memory.',
    approved_mother_terms: ['kayvot'],
    approved_folklore_entries: ['Iraya Cliff Song'],
    entries_revised: ['vahay'],
  },
  {
    username: 'paolo.banez',
    first_name: 'Paolo',
    last_name: 'Banez',
    municipality: 'Basco',
    affiliation: 'Sample Contributor',
    occupation: 'Youth Volunteer',
    bio: 'Helps draft entries for words younger speakers still hear but may not define confidently.',
    joined_date: '2026-03-08',
    photoIndex: 6,
    contributor_accountability: 'Invited by reviewer.aimee',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 4, folklore_entries: 1, revisions: 2, total_contributions: 7 },
    contributor_level: { title: 'Youth Contributor', current_count: 7 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Focuses on the words younger speakers still encounter today.',
    approved_mother_terms: ['davay'],
    approved_folklore_entries: ['Basco Shore Memory'],
    entries_revised: ['yaru'],
  },
  {
    username: 'tess.mangahis',
    first_name: 'Tess',
    last_name: 'Mangahis',
    municipality: 'Ivana',
    affiliation: 'Sample Contributor',
    occupation: 'Community Volunteer',
    bio: 'Contributes family sayings and example sentences grounded in daily life.',
    joined_date: '2026-03-08',
    photoIndex: 7,
    contributor_accountability: 'Invited by consultant.leo',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 4, folklore_entries: 1, revisions: 1, total_contributions: 6 },
    contributor_level: { title: 'Saying Gatherer', current_count: 6 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Helps entries sound like they still belong in a living conversation.',
    approved_mother_terms: ['tamid'],
    approved_folklore_entries: ['Ivana Family Saying'],
    entries_revised: ['chirin'],
  },
  {
    username: 'jerin.galimba',
    first_name: 'Jerin',
    last_name: 'Galimba',
    municipality: 'Mahatao',
    affiliation: 'Sample Contributor',
    occupation: 'Research Aide',
    bio: 'Supports entry cleanup and municipality tagging for local words.',
    joined_date: '2026-03-09',
    photoIndex: 8,
    contributor_accountability: 'Invited by consultant.marinel',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 3, folklore_entries: 1, revisions: 2, total_contributions: 6 },
    contributor_level: { title: 'Entry Organizer', current_count: 6 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Helps keep entries orderly and municipality-aware.',
    approved_mother_terms: ['sibatan'],
    approved_folklore_entries: ['Mahatao Ridge Story'],
    entries_revised: ['rayu'],
  },
  {
    username: 'mia.lanot',
    first_name: 'Mia',
    last_name: 'Lanot',
    municipality: 'Uyugan',
    affiliation: 'Sample Contributor',
    occupation: 'Student Volunteer',
    bio: 'Enjoys helping folklore and dictionary entries feel welcoming to first-time readers.',
    joined_date: '2026-03-09',
    photoIndex: 9,
    contributor_accountability: 'Invited by reviewer.luz',
    reviewer_accountability: 'Not currently serving as reviewer',
    contribution_summary: { dictionary_terms: 3, folklore_entries: 1, revisions: 1, total_contributions: 5 },
    contributor_level: { title: 'Welcoming Voice', current_count: 5 },
    reviewer_level: { title: 'Not yet active', current_count: 0 },
    language_headline: 'Brings a reader-friendly tone to sample contributions.',
    approved_mother_terms: ['hunget'],
    approved_folklore_entries: ['Uyugan Evening Tale'],
    entries_revised: ['mayuh'],
  },
]

function entryRows(terms, prefix, status = 'approved') {
  return (terms || []).map((label, index) => ({
    entry_id: `${prefix}-${index + 1}`,
    term: label,
    title: label,
    status,
  }))
}

function buildSampleProfile(seed) {
  return {
    header: {
      username: seed.username,
      first_name: seed.first_name,
      last_name: seed.last_name,
      profile_photo: '',
      sample_profile_photo_index: seed.photoIndex,
      municipality: seed.municipality,
      affiliation: seed.affiliation,
      occupation: seed.occupation,
      bio: seed.bio,
      joined_date: seed.joined_date,
      onboarding_accountability: {
        contributor: seed.contributor_accountability,
        reviewer: seed.reviewer_accountability,
      },
    },
    contribution_summary: seed.contribution_summary,
    gamification: {
      contributor_level: seed.contributor_level,
      reviewer_level: seed.reviewer_level,
      language: {
        headline: seed.language_headline,
      },
      dictionary_badges: DEFAULT_DICTIONARY_BADGES,
      folklore_badges: DEFAULT_FOLKLORE_BADGES,
      quality_badges: DEFAULT_QUALITY_BADGES,
    },
    lists: {
      approved_mother_terms: entryRows(seed.approved_mother_terms, `${seed.username}-dict`),
      approved_folklore_entries: entryRows(seed.approved_folklore_entries, `${seed.username}-folk`),
      entries_revised: entryRows(seed.entries_revised, `${seed.username}-rev`, 'approved_under_review'),
    },
  }
}

export const SAMPLE_PUBLIC_PROFILES = SAMPLE_PROFILE_SEEDS.reduce((result, seed) => {
  result[seed.username] = buildSampleProfile(seed)
  return result
}, {})

export const SAMPLE_PROFILE_SUMMARIES = SAMPLE_PROFILE_SEEDS.map((seed) => ({
  username: seed.username,
  display_name: `${seed.first_name} ${seed.last_name}`.trim(),
  municipality: seed.municipality,
  affiliation: seed.affiliation,
  occupation: seed.occupation,
  bio: seed.bio,
  profile_photo_index: seed.photoIndex,
}))

export const SAMPLE_HOME_GLOBAL_ROWS = [
  { username: 'ysabel.delacruz', municipality: 'Basco', value: 84 },
  { username: 'mark.apuyan', municipality: 'Mahatao', value: 78 },
  { username: 'lian.darunday', municipality: 'Ivana', value: 75 },
  { username: 'celina.nuguit', municipality: 'Uyugan', value: 71 },
  { username: 'rogelio.casta', municipality: 'Sabtang', value: 69 },
  { username: 'nica.esguerra', municipality: 'Itbayat', value: 65 },
  { username: 'paolo.banez', municipality: 'Basco', value: 62 },
  { username: 'tess.mangahis', municipality: 'Ivana', value: 58 },
  { username: 'jerin.galimba', municipality: 'Mahatao', value: 56 },
  { username: 'mia.lanot', municipality: 'Uyugan', value: 53 },
].map((row) => {
  const profile = SAMPLE_PROFILE_SUMMARIES.find((item) => item.username === row.username)
  return {
    ...row,
    display_name: profile?.display_name || row.username,
    profile_photo_index: profile?.profile_photo_index ?? 0,
  }
})

export function getSamplePublicProfile(username) {
  return SAMPLE_PUBLIC_PROFILES[(username || '').trim().toLowerCase()] || null
}

export function getSampleProfileSummary(username) {
  return SAMPLE_PROFILE_SUMMARIES.find((item) => item.username === username) || null
}
